Added automatically set data to next week
alanyee/valorantbp pull request #34
Opened 2023-10-02 10:58 UTC by SasikaSankalana

# Description

Fixes #31 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-02 19:00 UTC, alanyee requested changes

2023-10-02 19:00 UTC, alanyee commented on valorant/valorant.py
> +
The linter did not like this additional blank line. Can you remove it? I think I can approve and merge after this line is removed.

2023-10-03 04:18 UTC, SasikaSankalana commented
@alanyee Removed the line.

2023-10-03 06:17 UTC, alanyee approved these changes

2023-10-03 06:17 UTC, merged

2023-10-03 08:43 UTC, SasikaSankalana commented
@alanyee can you label thia as hacktoberfest-accepted